### ISSUE TITLE
Support of OpenAPI 3.0

### ISSUE THREAD

**Issue by developerpat** [segpacto/gql-gateway#11]
Hi,
will there also be a OpenAPI 3.0 Support?
It works with 3.0 but the definitions section is replaced by components in the new specification and so the type are not resolved. They are just String.

Looking forward to hear from you.

**Comment by segpacto** [comment]
Hello @developerpat,
Had been sometime already since your message. 
There is already an [alpha version](https://www.npmjs.com/package/gql-gateway/v/2.0.0-alpha0) that supports already OpenApi 3.0.
This version will be release soon as v2 of the package.
Feel free to try it out.
