### ISSUE TITLE
Collaborating with GraphQL Mesh

### ISSUE THREAD

**Issue by Urigo** [segpacto/gql-gateway#12]
HI @segpacto , I've just found your amazing library!

It seems like a very similar idea to what we are doing in [GraphQL Mesh](https://github.com/urigo/graphql-mesh)!
(you can read more [here and in the blog post](https://twitter.com/UriGoldshtein/status/1242118500795236353))

Do you think we could merge our efforts and work together?

**Comment by segpacto** [comment]
Hello Urigo,

Thanks for the feedback. 

Your product looks really good. I actually read an article about it 3-3 days ago and find it really interesting. I would be more than interested in joining efforts.

Do you have any particular area or topics in mind ?

**Comment by Urigo** [comment]
Theoretically we are solving the same issue and also in the same way!

Some differences I see are:

1. We use IBM's openapi to GraphQL convertor (with some changes we are contributing back) and you are using `swagger-to-graphql`
2. We are using the new version of schema stitching from `graphql-tools-fork` and you are using `graphql-tools`
3. We generate type safe resolvers and you are using JS
4. We do the same approach for other protocols as well (gRPC, SOAP, etc...)
5. We also provide an option to merge types using Federation metadata instead of schema stitching

I think first thing would be to see if you think we would be able to cover all the functionality here with our Swagger/OpenAPI handler?
Second would be, if you think the interface and API we've created are good or could be improved from the ideas you had here?

By looking at the differences we can decide how to move forward and how to make sure we can both help each!

**Comment by segpacto** [comment]
Hello Urigo,

> I think first thing would be to see if you think we would be able to cover all the functionality here with our Swagger/OpenAPI handler?
 
As far as I can see yes, one way or another with your tool the majority of cases can be covered.

> Second would be, if you think the interface and API we've created are good or could be improved from the ideas you had here?

I think the tool created by me is still on its beginnings and even when is quite flexible(at least from my point) needs to point to those new cases I could find. You cover a wider range of cases.

After reviewing both tools, I think it would help to see based on the usage and features request what could be those points that can be improved. My tool was born out of necessity and that guided me, so, on this moment features are tied to some business cases I locally have.

Let's keep in touch if something new comes and I will definitely let you know.
Keep the awesome work

**Comment by Urigo** [comment]
thank you for your comments!
looking forward to share ideas and see where the paths leads our libraries!
