### ISSUE TITLE
Introspection

### ISSUE THREAD

**Issue by Snarik** [segpacto/gql-gateway#21]
Hey folks, Im trying to use gql-gateway with an apollo federator. Does gql-gateway support introspection? We're currently doing a sort of weird schema generation process that is making things rather complicated. Would be awesome if we could just introspect the service.

**Comment by segpacto** [comment]
Hello @Snarik,
Yes, it does support introspection.
The package allows to pass all the configuration available for apollo-server. You can take a look at [configuration params](https://github.com/segpacto/gql-gateway#configuration-options-explained).
You can set under `apolloServerConfig` the `introspection`.

```
...

const apolloServerConfig = {
  playground: { endpoint: 'gql-gateway' },
  introspection: true
}

gateway({ resolvers, localSchema, endpointsList, apolloServerConfig })
...
```
