### ISSUE TITLE
[Question] How to forward headers to rest endpoints

### ISSUE THREAD

**Issue by dominicfollett** [segpacto/gql-gateway#23]
Hi, thank you for your very helpful package. I'm looking for help and am a bit new to Apollo in general.
I'd like to be able to set/configure headers on outgoing requests using the `willSendRequest` method usually defined on the RESTDataSource, like this:

```
willSendRequest({ request, context }) {
    const headers = context.requestHeaders;
    for (const key in headers) {
      const value = headers[key];
      if (value) {
        request.http?.headers.set(key, String(value));
      }
    }
  }
```

But I don't know how to do this using your package. Could you provide me with some guidance? Thank you in advance for your help.

**Comment by segpacto** [comment]
Hello @dominicfollett 

Currently the parameters of the incoming request(**headers included**) are forwarded to outgoing requests.
In case you want to set/configure it with other values you can use the plugins system of apollo server:
```
const gateway = require('gql-gateway')

const port = 5001

const endpointsList = [
  { name: 'petstore_service', url: 'https://petstore.swagger.io/v2/swagger.json' },
  { name: 'fruits_service', url: 'https://api.predic8.de/shop/swagger' }
]

const apolloServerConfig = {
    plugins: [{
        async requestDidStart ({context}) {
            context.req.headers['Authorization'] = 'Bearer XXXXX'
            context.req.headers['x-access-key'] = 'ApiKey MySpecialKey'
          }
    }]
}

gateway({ endpointsList, apolloServerConfig })
  .then(server => server.listen(port))
  .then(console.log(`Service is now running at port: ${port}`))
  .catch(err => console.log(err))
```

Notice that everything that is attached to the `context.req` is going to be part of the outgoing request.

Let me know if the example above helps.

**Comment by dominicfollett** [comment]
Thank you for your help!
